// Traditional Chinese UTF-8; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 UTF-8 ；數位應用坊製作； twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('advlink',{
general_tab : '一般',
popup_tab : '彈跳視窗',
events_tab : '事件',
advanced_tab : '進階',
general_props : '一般屬性',
popup_props : '彈跳視窗屬性',
event_props : '事件屬性',
advanced_props : '進階屬性',
popup_opts : '彈跳視窗選項',
anchor_names : '連結錨點',
target_same : '於此視窗或框架中開啟',
target_parent : '於上層視窗或框架中開啟',
target_top : '於主框架中開啟（會取代全部框架）',
target_blank : '於新視窗中開啟',
popup : 'Javascript 彈跳視窗',
popup_url : '彈跳視窗網址',
popup_name : '視窗名稱',
popup_return : '插入 "禁回上頁"',
popup_scrollbars : '顯示捲動軸',
popup_statusbar : '顯示狀態列',
popup_toolbar : '顯示工具列',
popup_menubar : '顯示選單列',
popup_location : '顯示網址列',
popup_resizable : '可調整視窗大小',
popup_dependent : '從屬性（僅適用 Mozilla / Firefox ）',
popup_size : '尺寸',
popup_position : '位置（ X / Y 軸）',
id : 'ID',
style: 'Style',
classes : 'Class',
target_name : '目標頁名稱',
langdir : '文字方向',
target_langcode : '目標頁語言',
langcode : '語言編碼',
encoding : '目標頁字元編碼',
mime : '目標頁 MIME 型式',
rel : '將網頁與目標頁產生關聯',
rev : '將目標頁與網頁產生關聯',
tabindex : '標籤索引',
accesskey : '存取鍵',
ltr : '由左至右',
rtl : '由右至左'
});
