// Simplified Chinese lang variables contributed by TinyMCE_China_Team ( tinymce_china {AT} yahoogroups {DOT} com ).
// visit our homepage at: http://www.cube316.net/tinymce/ for more information.

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '进阶',
general_props : '一般属性',
advanced_props : '进阶属性',
desc : '插入新表格',
row_before_desc : '在之前插入横行',
row_after_desc : '在之后插入横行',
delete_row_desc : '删除横行',
col_before_desc : '在之前插入直列',
col_after_desc : '在之后插入直列',
delete_col_desc : '删除直列',
rowtype : '表格中的直列',
title : '插入/调整表格',
width : '宽度',
height : '高度',
cols : '直列',
rows : '横行',
cellspacing : '框线间距',
cellpadding : '内文间距',
border : '框线',
align : '位置',
align_default : '内定',
align_left : '靠左对齐',
align_right : '靠右对齐',
align_middle : '置中对齐',
row_title : '横行属性',
cell_title : '储存格属性',
cell_type : '储存格类型',
row_desc : '横行属性',
cell_desc : '储存格属性',
valign : '垂直位置',
align_top : '靠上对齐',
align_bottom : '靠下对齐',
props_desc : '表格属性',
bordercolor : '框线颜色',
bgcolor : '背景颜色',
merge_cells_title : '合并储存格',
split_cells_desc : '分割储存格',
merge_cells_desc : '合并储存格',
cut_row_desc : '剪下横行',
copy_row_desc : '复制横行',
paste_row_before_desc : '在之前贴上横行',
paste_row_after_desc : '在之后贴上横行',
id : 'ID',
style: 'Style',
langdir : '语言方向',
langcode : '语言编码',
mime : '对象 MIME 类型',
ltr : '由左至右',
rtl : '由右至左',
bgimage : '背景图片',
summary : '一览',
td : "资料",
th : "表头",
cell_cell : '更新所在的储存格',
cell_row : '更新直列内的储存格',
cell_all : '更新表格中的储存格',
row_row : '更新所在的横行',
row_odd : '更新表格中的奇数横行',
row_even : '更新表格中的偶数横行',
row_all : '更新表格中的横行',
thead : '表格表头',
tbody : '表格实体',
tfoot : '表格表尾',
del : '删除表格',
scope : '范围',
row : '横行',
col : '直列',
rowgroup : '群组横行',
colgroup : '群组直列',
missing_scope: '确定要在没有对此表格标头设定范围下继续执行吗？\n不加以设定的话，可能会导致某些使用者无法顺利读取表格中的部份或是整体资讯。'
});
