// Traditional Chinese UTF-8; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 UTF-8 ；數位應用坊製作； twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '進階',
general_props : '一般屬性',
advanced_props : '進階屬性',
desc : '插入新表格',
row_before_desc : '在之前插入橫行',
row_after_desc : '在之後插入橫行',
delete_row_desc : '刪除橫行',
col_before_desc : '在之前插入直列',
col_after_desc : '在之後插入直列',
delete_col_desc : '刪除直列',
rowtype : '表格中的直列',
title : '插入/調整表格',
width : '寬度',
height : '高度',
cols : '直列',
rows : '橫行',
cellspacing : '框線間距',
cellpadding : '內文間距',
border : '框線',
align : '位置',
align_default : '內定',
align_left : '靠左對齊',
align_right : '靠右對齊',
align_middle : '置中對齊',
row_title : '橫行屬性',
cell_title : '儲存格屬性',
cell_type : '儲存格類型',
row_desc : '橫行屬性',
cell_desc : '儲存格屬性',
valign : '垂直位置',
align_top : '靠上對齊',
align_bottom : '靠下對齊',
props_desc : '表格屬性',
bordercolor : '框線顏色',
bgcolor : '背景顏色',
merge_cells_title : '合併儲存格',
split_cells_desc : '分割儲存格',
merge_cells_desc : '合併儲存格',
cut_row_desc : '剪下橫行',
copy_row_desc : '複製橫行',
paste_row_before_desc : '在之前貼上橫行',
paste_row_after_desc : '在之後貼上橫行',
id : 'ID',
style: 'Style',
langdir : '語言方向',
langcode : '語言編碼',
mime : '對象 MIME 類型',
ltr : '由左至右',
rtl : '由右至左',
bgimage : '背景圖片',
summary : '一覽',
td : "資料",
th : "表頭",
cell_cell : '更新所在的儲存格',
cell_row : '更新直列內的儲存格',
cell_all : '更新表格中的儲存格',
row_row : '更新所在的橫行',
row_odd : '更新表格中的奇數橫行',
row_even : '更新表格中的偶數橫行',
row_all : '更新表格中的橫行',
thead : '表格表頭',
tbody : '表格實體',
tfoot : '表格表尾',
del : '刪除表格',
scope : '範圍',
row : '橫行',
col : '直列',
rowgroup : '群組橫行',
colgroup : '群組直列',
missing_scope: '確定要在沒有對此表格標頭設定範圍下繼續執行嗎？\n不加以設定的話，可能會導致某些使用者無法順利讀取表格中的部份或是整體資訊。'
});
