// UK lang variables

tinyMCE.addToLang('media',{
title : '插入/編輯嵌入媒體',
desc : '插入/編輯嵌入媒體',
general : '一般',
advanced : '進階',
file : '檔案',
list : '列表',
size : '規格',
preview : '預覽',
constrain_proportions : '強制大小比例',
type : '類型',
id : 'Id',
name : '名稱',
class_name : '類別',
vspace : '寬度',
hspace : '高度',
play : '自動撥放',
loop : '重覆撥放',
menu : '顯示選單',
quality : '品質',
scale : '規格',
align : '對齊',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : '背景',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : '快取',
hidden : '隱藏',
controller : '控制品',
kioskmode : 'Kiosk mode',
playeveryframe : '撥放每個影格',
targetcache : '目標快取',
correction : '不校正',
enablejavascript : '啟用 JavaScript',
starttime : '開始時間',
endtime : '結束時間',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : '目標',
volume : 'Volume',
autostart : '自動開始',
enabled : '啟用',
fullscreen : '全螢幕',
invokeurls : '觸發 URLs',
mute : '無聲',
stretchtofit : '調整至合適',
windowlessvideo : 'Windowless video',
balance : '平衝',
baseurl : 'Base URL',
captioningid : 'Captioning id',
currentmarker : 'Current marker',
currentposition : 'Current position',
defaultframe : 'Default frame',
playcount : 'Play count',
rate : 'Rate',
uimode : 'UI Mode',
flash_options : 'Flash 選項',
qt_options : 'Quicktime 選項',
wmp_options : 'Windows media player 選項',
rmp_options : 'Real media player 選項',
shockwave_options : 'Shockwave 選項',
autogotourl : '自動連至的URL',
center : '置中',
imagestatus : '圖片狀態',
maintainaspect : 'Maintain aspect',
nojava : '不使用java',
prefetch : 'Prefetch',
shuffle : 'Shuffle',
console : '控制台',
numloop : '重覆次數',
controls : 'Controls',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : '聲音',
progress : '進度',
qtsrc : 'QT Src',
qt_stream_warn : 'Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..'
});
