// TW lang variables

tinyMCE.addToLang('style',{
title : '编辑 CSS Style',
styleinfo_desc : '编辑 CSS Style',
text_tab : '类型',
background_tab : '背景',
block_tab : '区块',
box_tab : '方框',
border_tab : '边框',
list_tab : '清单',
positioning_tab : '定位',
text_props : 'Text',
text_font : '字型',
text_size : '大小',
text_weight : '粗细',
text_style : '样式',
text_variant : '变型',
text_lineheight : '行高',
text_case : '大小写',
text_color : '颜色',
text_decoration : '装饰',
background_color : '背景颜色',
background_image : '背景影像',
background_repeat : '重复',
background_attachment : '附件',
background_hpos : '水平位置',
background_vpos : '垂直位置',
block_wordspacing : '单字间距',
block_letterspacing : '字母间距',
block_vertical_alignment : '垂直对齐',
block_text_align : '文字对齐',
block_text_indent : '文字缩排',
block_whitespace : '空白',
block_display : '显示',
box_width : '宽',
box_height : '高',
box_float : '浮动',
box_clear : '清除',
padding : '栏位间隔',
same : '全部一样',
top : '上',
right : '右',
bottom : '下',
left : '左',
margin : '边界',
style : '样式',
width : '宽度',
height : 'Height',
color : '颜色',
list_type : '类型',
bullet_image : '项目符号影像',
position : '位置',
positioning_type : '类型',
visibility : '显示',
zindex : 'Z 轴',
overflow : '溢位',
placement : '置入',
clip : '裁切'
});
