// TW lang variables

tinyMCE.addToLang('style',{
title : '編輯 CSS Style',
styleinfo_desc : '編輯 CSS Style',
apply : '套用',
text_tab : '類型',
background_tab : '背景',
block_tab : '區塊',
box_tab : '方框',
border_tab : '邊框',
list_tab : '清單',
positioning_tab : '定位',
text_props : 'Text',
text_font : '字型',
text_size : '大小',
text_weight : '粗細',
text_style : '樣式',
text_variant : '變型',
text_lineheight : '行高',
text_case : '大小寫',
text_color : '顏色',
text_decoration : '裝飾',
text_overline : '上端線',
text_underline : '底線',
text_striketrough : '刪除線',
text_blink : '閃爍',
text_none : '無',
background_color : '背景顏色',
background_image : '背景影像',
background_repeat : '重複',
background_attachment : '附件',
background_hpos : '水平位置',
background_vpos : '垂直位置',
block_wordspacing : '單字間距',
block_letterspacing : '字母間距',
block_vertical_alignment : '垂直對齊',
block_text_align : '文字對齊',
block_text_indent : '文字縮排',
block_whitespace : '空白',
block_display : '顯示',
box_width : '寬',
box_height : '高',
box_float : '浮動',
box_clear : '清除',
padding : '欄位間隔',
same : '全部一樣',
top : '上',
right : '右',
bottom : '下',
left : '左',
margin : '邊界',
style : '樣式',
width : '寬度',
height : '高度',
color : '顏色',
list_type : '類型',
bullet_image : '項目符號影像',
position : '位置',
positioning_type : '類型',
visibility : '顯示',
zindex : 'Z 軸',
overflow : '溢位',
placement : '置入',
clip : '裁切'
});
