/**
 * RokNewsRotator - A news rotator with prev/next implementation and ability to play/stop.
 * 
 * @version		1.5
 * 
 * @license		MIT-style license
 * @author		Djamil Legato <djamil [at] djamil.it>
 * @client		Andy Miller @ Rockettheme
 * @copyright	Author
 */

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('g 1a=a 1d({1g:\'1.5\',8:{w:1h,17:1e,1c:M,X:E,f:E,Y:E,12:0.7,I:\'d/1k.1v\'},1l:6(r,8){3.r=$(r);3.1r(8);3.d=3.r.1q(\'.U > L\');3.b=$$(\'#\'+r+\' .q-11 .1n D.q D.1p\');3.l=0;3.10();3.13();3.z=\'m\';n(3.8.1c)1s.F(\'1o\',3.e.k(3));h 3},10:6(){g s=3;$$(3.b,3.d).H(\'1m\',\'1u\');g d=3.d.P(1);g b=3.b.P(1);d.p(6(U){U.Z(3.d[0]).H(\'C\',0)},3);b.p(6(q){q.Z(3.b[0]).H(\'C\',0)},3);g W=$$(\'.q-11\').P(1);W.p(6(q){q.1i().1j()});g f=a u(\'D\',{\'t\':\'f\'}).x(3.r);3.15=a u(\'L\',{\'t\':\'y-A\',\'S\':\'1f\',\'Q\':\'A\',\'R\':3.8.I}).x(f);3.14=a u(\'L\',{\'t\':\'y-o\',\'S\':\'1t\',\'Q\':\'o\',\'R\':3.8.I}).x(f);3.16=a u(\'L\',{\'1F\':\'e-m\',\'t\':\'y-m\',\'S\':\'1N/1O\',\'Q\':\'e/m\',\'R\':3.8.I}).x(f);n(!3.8.f)f.H(\'1I\',\'1K\');n(3.8.Y&&3.8.f){g B=a N.O(f,\'C\',{1J:M}).1H(0);3.r.1L({\'1M\':B.v.k(B,3.8.12),\'1P\':B.v.k(B,0)})};n(3.8.X){(3.d.G).J(6(i){(2).J(6(j){a u(\'D\',{\'t\':\'i\'+(j+1)}).x(3.d[i])}.k(3))}.k(3))}(4).J(6(i){a u(\'D\',{\'t\':\'1w c\'+(i+1)}).x(3.b[0].1z())}.k(3));3.9=[];(3.b.G).J(6(i){3.9[i]=[a N.O(3.d[i],\'C\',{w:3.8.w,1y:6(){s.K=E},1x:6(){s.K=M}}),a N.O(3.b[i],\'C\',{w:3.8.w})]}.k(3));h 3},13:6(){g s=3,T=$(\'e-m\');3.15.F(\'V\',3.18.k(3));3.14.F(\'V\',3.o.k(3));3.16.F(\'V\',6(){n(s.z==\'e\'){s.m();T.19=\'y-e\'}1A{s.e();T.19=\'y-m\'}});h 3},18:6(){n(3.K)h 3;g A=(!3.l)?3.b.G-1:3.l-1;3.9[3.l].p(6(9){9.v(0)});3.9[A].p(6(9){9.v(1)});3.l=A;h 3},o:6(){n(3.K)h 3;g o=(3.l==3.b.G-1)?0:3.l+1;3.9[3.l].p(6(9){9.v(0)});3.9[o].p(6(9){9.v(1)});3.l=o;h 3},e:6(){n(3.z==\'e\')h 3;3.z=\'e\';3.1b=3.o.1B(3.8.17+3.8.w,3);h 3},m:6(){3.z=\'m\';$1E(3.1b);h 3}});1a.1D(a 1C,a 1G);',62,114,'|||this|||function||options|fx|new|content||images|play|controls|var|return|||bind|current|stop|if|next|each|story|container|self|class|Element|start|duration|inject|control|status|prev|controlsFx|opacity|div|true|addEvent|length|setStyle|blankimage|times|transitioning|img|false|Fx|Style|slice|alt|src|title|playstop|image|click|stories|corners|autohide|injectAfter|build|block|fadeIn|attachEvents|arrowNext|arrowPrev|arrowPlay|delay|previous|className|RokNewsRotator|timer|autoplay|Class|5000|Previous|version|1000|empty|remove|blank|initialize|position|divider|load|padding|getElements|setOptions|window|Next|absolute|png|corner|onComplete|onStart|getParent|else|periodical|Events|implement|clear|id|Options|set|display|wait|none|addEvents|mouseenter|Play|Stop|mouseleave'.split('|'),0,{}))
