// UK lang variables

tinyMCE.addToLang('media',{
title : '插入/编辑嵌入媒体',
desc : '插入/编辑嵌入媒体',
general : '一般',
advanced : '进阶',
file : '档案',
list : '列表',
size : '规格',
preview : '预览',
constrain_proportions : '强制大小比例',
type : '类型',
id : 'Id',
name : '名称',
class_name : '类别',
vspace : '宽度',
hspace : '高度',
play : '自动拨放',
loop : '重覆拨放',
menu : '显示选单',
quality : '品质',
scale : '规格',
align : '对齐',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : '背景',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : '快取',
hidden : '隐藏',
controller : '控制品',
kioskmode : 'Kiosk mode',
playeveryframe : '拨放每个影格',
targetcache : '目标快取',
correction : '不校正',
enablejavascript : '启用 JavaScript',
starttime : '开始时间',
endtime : '结束时间',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : '目标',
volume : 'Volume',
autostart : '自动开始',
enabled : '启用',
fullscreen : '全荧幕',
invokeurls : '触发 URLs',
mute : '无声',
stretchtofit : '调整至合适',
windowlessvideo : 'Windowless video',
balance : '平冲',
baseurl : 'Base URL',
captioningid : 'Captioning id',
currentmarker : 'Current marker',
currentposition : 'Current position',
defaultframe : 'Default frame',
playcount : 'Play count',
rate : 'Rate',
uimode : 'UI Mode',
flash_options : 'Flash 选项',
qt_options : 'Quicktime 选项',
wmp_options : 'Windows media player 选项',
rmp_options : 'Real media player 选项',
shockwave_options : 'Shockwave 选项',
autogotourl : '自动连至的URL',
center : '置中',
imagestatus : '图片状态',
maintainaspect : 'Maintain aspect',
nojava : '不使用java',
prefetch : 'Prefetch',
shuffle : 'Shuffle',
console : '控制台',
numloop : '重覆次数',
controls : 'Controls',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : '声音',
progress : '进度',
qtsrc : 'QT Src',
qt_stream_warn : 'Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..'
});
